[package]
name = "jinx"
version = "0.1.0"
authors = ["Jared De La Cruz <jared@jareddlc.com>"]
edition = "2018"

[dependencies]
crossterm = "0.16"
env_logger = "0.7"
handlebars = "3.0"
dirs = "2.0"
log = "0.4"
rs-docker = "0.0.58"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
tar = "0.4"
